# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-15 04:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docType', models.CharField(max_length=10)),
                ('requestReason', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advisor', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Student_Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_feedback', models.CharField(max_length=500)),
                ('sessionId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advisingplus.Session')),
            ],
        ),
        migrations.AddField(
            model_name='schedule',
            name='sessionId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advisingplus.Session'),
        ),
        migrations.AddField(
            model_name='notes',
            name='sessionId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advisingplus.Session'),
        ),
        migrations.AddField(
            model_name='documents',
            name='sessionId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advisingplus.Session'),
        ),
    ]
