# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-20 20:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('advisingplus', '0001_initial'), ('advisingplus', '0002_notes_content'), ('advisingplus', '0003_auto_20161119_2133'), ('advisingplus', '0004_auto_20161119_2135'), ('advisingplus', '0005_auto_20161119_2149'), ('advisingplus', '0006_auto_20161119_2201')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docType', models.CharField(max_length=10)),
                ('requestReason', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Student_Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_feedback', models.CharField(max_length=500)),
                ('sessionId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advisingplus.Session')),
            ],
        ),
        migrations.AddField(
            model_name='notes',
            name='sessionId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advisingplus.Session'),
        ),
        migrations.AddField(
            model_name='documents',
            name='sessionId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advisingplus.Session'),
        ),
        migrations.AddField(
            model_name='notes',
            name='content',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.CreateModel(
            name='Advisor_Timeslot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advisor', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='session',
            name='timeslot',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='advisingplus.Advisor_Timeslot'),
            preserve_default=False,
        ),
    ]
