# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 01:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advisor_Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Advisor_Timeslot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(blank=True)),
                ('advisor', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docType', models.CharField(max_length=10)),
                ('requestReason', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(blank=True, max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.CharField(blank=True, max_length=250)),
                ('timeslot', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='advisingplus.Advisor_Timeslot')),
            ],
        ),
        migrations.CreateModel(
            name='Student_Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_feedback', models.CharField(max_length=500)),
                ('sessionId', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='advisingplus.Session')),
            ],
        ),
        migrations.AddField(
            model_name='note',
            name='sessionId',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='advisingplus.Session'),
        ),
        migrations.AddField(
            model_name='document',
            name='sessionId',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='advisingplus.Session'),
        ),
    ]
