# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 00:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisingplus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='content',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
