# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 01:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisingplus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advisor_status',
            name='advisor_availability',
            field=models.BooleanField(default=None),
            preserve_default=False,
        ),
    ]
