# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-20 20:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('advisingplus', '0001_squashed_0006_auto_20161119_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='advisor_timeslot',
            name='date_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
