# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 01:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advisingplus', '0002_advisor_status_advisor_availability'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advisor_status',
            old_name='advisor_availability',
            new_name='advisor_availiable',
        ),
    ]
