# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-20 22:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advisingplus', '0002_advisor_timeslot_date_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docType', models.CharField(max_length=10)),
                ('requestReason', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(blank=True, max_length=400)),
            ],
        ),
        migrations.RemoveField(
            model_name='documents',
            name='sessionId',
        ),
        migrations.RemoveField(
            model_name='notes',
            name='sessionId',
        ),
        migrations.AlterField(
            model_name='session',
            name='student',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='session',
            name='timeslot',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='advisingplus.Advisor_Timeslot'),
        ),
        migrations.AlterField(
            model_name='student_feedback',
            name='sessionId',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='advisingplus.Session'),
        ),
        migrations.DeleteModel(
            name='Documents',
        ),
        migrations.DeleteModel(
            name='Notes',
        ),
        migrations.AddField(
            model_name='note',
            name='sessionId',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='advisingplus.Session'),
        ),
        migrations.AddField(
            model_name='document',
            name='sessionId',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='advisingplus.Session'),
        ),
    ]
