# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 01:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advisingplus', '0003_auto_20161201_0119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advisor_status',
            old_name='advisor_availiable',
            new_name='advisor_availability',
        ),
        migrations.AlterField(
            model_name='advisor_timeslot',
            name='advisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
