# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 21:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advisingplus', '0003_auto_20161119_2133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='Advisor_Timeslot',
        ),
        migrations.AddField(
            model_name='session',
            name='timeslot',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='advisingplus.Advisor_Timeslot'),
            preserve_default=False,
        ),
    ]
