# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 21:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisingplus', '0004_auto_20161119_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='advisor_timeslot',
            name='StartTime',
            field=models.TimeField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advisor_timeslot',
            name='date',
            field=models.DateField(default=2),
            preserve_default=False,
        ),
    ]
