# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 06:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advisingplus', '0005_auto_20161201_0319'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student_Feedback',
            new_name='Feedback',
        ),
        migrations.RenameModel(
            old_name='Advisor_Status',
            new_name='Status',
        ),
        migrations.RenameModel(
            old_name='Advisor_Timeslot',
            new_name='Timeslot',
        ),
    ]
