# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 22:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advisingplus', '0005_auto_20161119_2149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advisor_timeslot',
            name='StartTime',
        ),
        migrations.RemoveField(
            model_name='advisor_timeslot',
            name='date',
        ),
    ]
