# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 09:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advisingplus', '0006_auto_20161201_0658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='advisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
