# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 12:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advisingplus', '0008_auto_20161201_1019'),
    ]

    operations = [
        migrations.RenameField(
            model_name='status',
            old_name='advisor_availability',
            new_name='advisor_available',
        ),
    ]
